# Generated by Django 5.2.6 on 2025-09-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
