# Generated by Django 5.2.6 on 2025-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for Under Construction mode', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End data and time  for Under Construction mode', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
